#!/bin/bash
 cd /home/pi
          git clone https://github.com/RaspberryRBX/Spotify.git
          cd Spotify
          mkdir /home/pi/.local/share/Spotify
          sudo mv /home/pi/Spotify/Spotify.desktop /usr/share/applications
          sudo mv /home/pi/Spotify/spotify.png /usr/share/icons
          sudo mv /home/pi/Spotify/spotify.sh /home/pi/.local/share/Spotify
          sudo rm -f README.md
          cd /home/pi
sudo rm --dir Spotify