#!/bin/bash
          cd /home/pi
          mkdir /home/pi/.local/share/Spotify
          sudo mv /home/pi/Spotify/Spotify.desktop /usr/share/applications
          sudo mv /home/pi/Spotify/spotify.png /usr/share/icons
          sudo mv /home/pi/Spotify/spotify.sh /home/pi/.local/share/Spotify
          cd /home/pi/.local/share/Spotify
          sudo chmod +x spotify.sh
          ./spotify.sh
          cd
          clear
          echo This Script Was Created By RaspberryRBX And Someone From Pilabs Discord
