#!/bin/bash
 sudo rm -f /usr/share/applications/Spotify.desktop
          sudo rm -f /usr/share/icons/spotify.png
          sudo rm -f /home/pi/.local/share/Spotify/spotify.sh
          cd /home/pi
          sudo rm --dir /home/pi/.local/shareSpotify
